spring:
  datasource:
    url: jdbc:h2:mem:sajbot
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

weather:
  api-key: YOUR_OPENWEATHER_API_KEY
  location: "Brussels,BE"

electricity:
  price-url: "https://api.example.com/price"
